sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: dp0bI1BN0K/foOPgtX8SmKInPq0Ytw9QRkEgdaS4zrj93w08QTIfSVJ+Z7G+4iN2bk+vn7VyAtxOELYMbQ7xmmsNtr5U6PjRmtkIBMj9yT9D28aCa/edlxKTEmxtM/FQBcYNdDXz1/7RSLNKopY+xehX3rmQaLyzxRQpAjEVRTR6jAVZ9S9GH3x8ua1XqRSfJ9BcOysHOqPDx2QCSLdnYKn3U+qODSHzVLeyf6Bmc7HZ4W9umBP4qxqQ7AhhdndHzDmnOx/UjMbeiYY9fzR2CTS3kA3bt/vBYrp5c/dJMWuoWF70YXruryIfnprPONCDdaZWn6c2/S6qhEMlT1pTb55UyMD6T41PMxA5vtkpU6rK93fKsf7BGo4TeNxugKUB9F5nRsfmi7VIq8rT5JwV8jG4UDOC3WXKMMIZjTyMgQpQMeM1YREqxaVY4A5cl+Czy4DhOyXntQCtsfTy8qEdBmpYj3CT8/Elrgjvzd3Sj1xdndMvgMCyGyyYmcgxv9FoKLIWmXrPYFdAQayO8R2ix5nuJVOAFnLXoNZaoEpsc42rsEUx9O/QgZ93SIk7nd77rgJDKz+VYELgbkCK9GNHMGMWSt3OAv/gSqfPqoceMNa6w3NaGybqS4zVkIA9CIUe7GWxUuoihOqK5VLwOb0UclAEH5DMXRM2jn1XNLV8uxg=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: BRTZbfd1Yw3eUQy4yIWiJcM5vbnsngFZik6uJrOEW6aU7+ZY7xjHFt8UbPdmNP/+GlVtpGouX9TlDEXPlYUvI2m1e0aHQl4YSOZmHsowcJaLDEE5xHqRxI5+FgO3rC6iIOoaPLW6xR91Xh69PwVHucRdBcOthYjrEb3wzIgKvqV6q/SY7GFmC90Vm9d9I03ZDpsRqS1Ms9HJL1o+LQQqZLm+1i62w7VlVjIb3mpY8xoI8DPzkrQ7JV2G7aZSGsB9xuW/3WSfAUoUoUQlcdzI3NVjKXp3yOLvesQQmtjZn6FHaMbjYc96sDlLTO+G2ZqIQnfj5YDkqoYJZXQeH/nr9VlhUCK1wMXL9PmlE70y4hVjyV2I+q3AXzWkFEciqDUm0ZinB7yUhxKsD+dNv5aKxHZ6Q2kvqwat9P58nIVDs+wci1CE06EMsMKgaMSlHvV2opbjz44SQsxZSA2nPcWhR/ebtDFqRLyZx70XfaY37esEU5uP6YP1eRf4v0XHC5HdgK/OGw+qkwZke460luRx29WYOz8tz1KVQTg1zfm5A0q+VFRHl6IyCQf35HEw2n3/v+JPiRFs96e3rJBdwiioBwDB+DysnxjBuNbAIcSOUXgsp0QSJ4yZ/4B2gqjoTNXWTq8WGmGzWYKIG8o/Ttgi4Q2cOtsiFQHDRBoSTm45t+I=
